[tools]
java = "23"
jbang = "latest"
maven = "latest"
mvnd = "latest"

scala = "latest"
sbt = "latest"
coursier = "latest"

kotlin = "latest"
kscript = "latest"

python = "3.12"

node = "20"

[settings]
idiomatic_version_file_enable_tools = ["java"]
