#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Tunnelblick$" manage=off

yabai -m rule --add app="^Microsoft Outlook$" manage=off grid=1:1:1:1:1:1
yabai -m rule --add app="^Postbox$" manage=off grid=1:1:1:1:1:1
yabai -m rule --add app="^Remember The Milk$" manage=off grid=1:1:1:1:1:1
yabai -m rule --add app="^GIMP-" manage=off grid=1:1:1:1:1:1

