require('settings').setup()
require('plugin-manager').setup()
require('completion').setup()
require('lsp').setup()
require('statusline').setup()
require('mappings').setup()
require('filetypes').setup()
require('dependencies').setup()
