require('config.settings').setup()
require('config.lazy').setup()
require('config.mappings').setup()
require('config.commands').setup()
require('config.colorscheme').setup()
require('config.lsp').setup()
