" Generated by vim-plug
" Wed 15 Sep 2021 03:26:07 PM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['galaxyline.nvim'].commit = 'd544cb9d0b56f6ef271db3b4c3cf19ef665940d5'
silent! let g:plugs['gitsigns.nvim'].commit = 'daa233aabb4dbc7c870ea7300bcfeef96d49c2a3'
silent! let g:plugs['jqno-autoclose.vim'].commit = '8e379b5e701ec2e31b9ebbd5e4b69bb535954c91'
silent! let g:plugs['nord.nvim'].commit = '467d684f296a57b0069ff4ee9566df439511efe3'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-compe'].commit = 'ef97a9b17c655d8b603c5fa9abf6fbb623a1dad4'
silent! let g:plugs['nvim-dap'].commit = '344b6f0b581dd72e40bbbb78b4f147e5003e0ce6'
silent! let g:plugs['nvim-jdtls'].commit = '391e55bb5f90bc23e47c3b57eed6c6fcc95b0e7f'
silent! let g:plugs['nvim-lspconfig'].commit = 'f97aac6b717e904fe4d8ff58425651d5a802084e'
silent! let g:plugs['nvim-metals'].commit = '32fc0b137407b169e01cbc762844cdbfacacfe4f'
silent! let g:plugs['nvim-tree.lua'].commit = 'd3e76b81e5b169af192dea4da0bd6f64faad2c36'
silent! let g:plugs['nvim-treesitter'].commit = '27f5e99cdd1b4e7f6a5cc30016d990ebf81a561c'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '7f36db566c66998e04ea569723174c42d8190903'
silent! let g:plugs['plenary.nvim'].commit = '15c3cb9e6311dc1a875eacb9fc8df69ca48d7402'
silent! let g:plugs['popup.nvim'].commit = '5e3bece7b4b4905f4ec89bee74c09cfd8172a16a'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = 'dcee6c81f4cd5f9bc4a4cea782135a0669aa74bd'
silent! let g:plugs['terminus'].commit = 'e8bc19c8156d955762c31d0964eeb7c84889f42e'
silent! let g:plugs['ultisnips'].commit = 'aec91caefec10741722927cf073703a528fe7a8f'
silent! let g:plugs['vim-closetag'].commit = 'c0779ef575d5c239162f4ca3506cfb4a95d45a58'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-cool'].commit = '27ad4ecf7532b750fadca9f36e1c5498fc225af2'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-gutentags'].commit = '50705e8ebb7038b31314f416d1bddd9cb9154049'
silent! let g:plugs['vim-lastplace'].commit = '8f6c4454eb462776b6ebdc48e3e29a68ddeb726d'
silent! let g:plugs['vim-numbertoggle'].commit = '075b7478777e694fbac330ee34a74590dad0fee1'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'
silent! let g:plugs['which-key.nvim'].commit = 'dc9c3be7acae2a486c117f5a9f6ada62b2243336'
silent! let g:plugs['wildfire.vim'].commit = 'fa91b732fd1c5acd23b7b32d5fbbc884eedafc8d'
silent! let g:plugs['zen-mode.nvim'].commit = '21ca264c6ae934ceac220cf719c0ed6c0216b057'

PlugUpdate!

