" Generated by vim-plug
" Fri 01 Oct 2021 08:25:34 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['everforest'].commit = '967b408db4d78bee2145be0a5b398b127f92374a'
silent! let g:plugs['galaxyline.nvim'].commit = 'd544cb9d0b56f6ef271db3b4c3cf19ef665940d5'
silent! let g:plugs['gitsigns.nvim'].commit = 'daa233aabb4dbc7c870ea7300bcfeef96d49c2a3'
silent! let g:plugs['jqno-autoclose.vim'].commit = '8e379b5e701ec2e31b9ebbd5e4b69bb535954c91'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-compe'].commit = 'ef97a9b17c655d8b603c5fa9abf6fbb623a1dad4'
silent! let g:plugs['nvim-dap'].commit = '409fd0cfbaa39e52e02c06eeae5456cadb0b6748'
silent! let g:plugs['nvim-jdtls'].commit = 'adeca37bd8ac86ec1782f1a9f270827e7a64dac3'
silent! let g:plugs['nvim-lspconfig'].commit = 'a7df46eead286734203b1f7b71141fb131743d40'
silent! let g:plugs['nvim-metals'].commit = '32fc0b137407b169e01cbc762844cdbfacacfe4f'
silent! let g:plugs['nvim-tree.lua'].commit = '1b04082872aaa4b58f0259a2b049402a88be67b6'
silent! let g:plugs['nvim-treesitter'].commit = '47cfda2c6711077625c90902d7722238a8294982'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '47cdd6befd74cad188ed331fce8a951d98f9c4e3'
silent! let g:plugs['plenary.nvim'].commit = '6bb0e09030a7c2af19bf288088ca815228de9429'
silent! let g:plugs['popup.nvim'].commit = 'f91d80973f80025d4ed00380f2e06c669dfda49d'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = '440c598de419858a056e7d9d42a0a6829cd5bb05'
silent! let g:plugs['terminus'].commit = 'e8bc19c8156d955762c31d0964eeb7c84889f42e'
silent! let g:plugs['ultisnips'].commit = 'aec91caefec10741722927cf073703a528fe7a8f'
silent! let g:plugs['vim-closetag'].commit = 'c0779ef575d5c239162f4ca3506cfb4a95d45a58'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-cool'].commit = '27ad4ecf7532b750fadca9f36e1c5498fc225af2'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-gutentags'].commit = '50705e8ebb7038b31314f416d1bddd9cb9154049'
silent! let g:plugs['vim-lastplace'].commit = '8f6c4454eb462776b6ebdc48e3e29a68ddeb726d'
silent! let g:plugs['vim-numbertoggle'].commit = '075b7478777e694fbac330ee34a74590dad0fee1'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'
silent! let g:plugs['which-key.nvim'].commit = 'dc9c3be7acae2a486c117f5a9f6ada62b2243336'
silent! let g:plugs['wildfire.vim'].commit = 'fa91b732fd1c5acd23b7b32d5fbbc884eedafc8d'
silent! let g:plugs['zen-mode.nvim'].commit = '21ca264c6ae934ceac220cf719c0ed6c0216b057'

PlugUpdate!

