# Install software here
cask_args appdir: '/Applications'

# Taps
tap "AdoptOpenJDK/openjdk"  # For versions, see: https://github.com/AdoptOpenJDK/homebrew-openjdk
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "olafurpg/scalafmt"
tap "scalacenter/bloop"

# Required for installing other things
brew "node"
brew "python"
brew "ruby"
cask "adoptopenjdk8"
cask "adoptopenjdk11"

# Software to install
brew "bat"
brew "ctags"
brew "figlet"
brew "fzf"
brew "git"
brew "gnupg"
brew "jq"
brew "maven"
brew "pandoc"
brew "rsync"
brew "sbt"
brew "scala"
brew "the_silver_searcher"
brew "tig"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

brew "heroku/brew/heroku"
brew "olafurpg/scalafmt/scalafmt", args: ["HEAD"]
brew "scalacenter/bloop/bloop"

cask "alfred"
cask "avast-security"
cask "bartender"
cask "dropbox"
cask "firefox"
cask "font-comic-neue"
cask "font-fira-code"
cask "gitup"
cask "google-chrome"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "macpass"
cask "macvim"
cask "microsoft-office"
cask "night-owl"
cask "rambox"
cask "rocket"
cask "spotify"
cask "tunnelblick"

mas "Airmail 3", id: 918858936
mas "NordVPN IKE", id: 1116599239
mas "Pixelmator", id: 407963104

