#!/usr/bin/env bash

TYPE="$1"
DEVICE="$2"
STATUS="$3"
DESCRIPTION="$4"


case "$TYPE,$STATUS" in
  keyboard,connected)
    "$HOME/scripts/manage_keyboard.sh" plug "$DEVICE" "$DESCRIPTION"
    ;;
  display,disconnected)
    xrandr --output "$DEVICE" --off
    ;;
  display,connected)
    "$HOME/scripts/manage_displays.sh"
    ;;
esac
