" Generated by vim-plug
" Fri Apr 23 14:49:49 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['galaxyline.nvim'].commit = 'cbf64bd4869c810b92f6450ed8763456c489be87'
silent! let g:plugs['gitsigns.nvim'].commit = '6b7b666cc95f91c869b1ef266e10f06807f7ccf0'
silent! let g:plugs['goyo.vim'].commit = 'a865dec7ca7616dbbd69315ad1417b84d0c411f8'
silent! let g:plugs['jqno-autoclose.vim'].commit = '479270a6d78e813e46a4b706566347909196f29f'
silent! let g:plugs['lspsaga.nvim'].commit = '2bc15f3c9851613fa29926780914d25ebc4b8c83'
silent! let g:plugs['nlua.nvim'].commit = 'c0e8fbcaf8bcf5571a9e1d780a72094aad3f3094'
silent! let g:plugs['nvcode-color-schemes.vim'].commit = '90ee71d66da58d57f0cb4a59103874bb519c79d4'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-compe'].commit = '888d9eccfe7b9092dcbfcdfabfad601ce63f3eb5'
silent! let g:plugs['nvim-dap'].commit = '0314abda6b654b7147580f0074716ff0e94592bc'
silent! let g:plugs['nvim-jdtls'].commit = 'e16fb1b9619e236a4c101593006ac279a48257b3'
silent! let g:plugs['nvim-lspconfig'].commit = '5029746a27ad817a9554b28d502d00f235fed39c'
silent! let g:plugs['nvim-metals'].commit = '381fd8c1a594a6b4ae7dd78d9b4522fc969beb15'
silent! let g:plugs['nvim-tree.lua'].commit = '090697e71fe614cc13f218fc751a651cf4fada4f'
silent! let g:plugs['nvim-treesitter'].commit = '2abad14069534f5589cab43f744cdf7be93a5464'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '83fab05478657bea1ee21405d5be530b35ae646f'
silent! let g:plugs['plenary.nvim'].commit = '1a31d076a097ac23c0110537a99b686874ae2cdc'
silent! let g:plugs['popup.nvim'].commit = 'bc98ca6df9179452c368f0d7bac821a8fd4c01ac'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = 'f2c3f724ad8c05f7001eb0f091ed210f02a62ca2'
silent! let g:plugs['terminus'].commit = '51c9bf43427af5ddff7352707a2bdab58cac9593'
silent! let g:plugs['ultisnips'].commit = 'b974a13328071de45a85c62ab65c8bfed0142728'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-cool'].commit = '27ad4ecf7532b750fadca9f36e1c5498fc225af2'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-gutentags'].commit = '50705e8ebb7038b31314f416d1bddd9cb9154049'
silent! let g:plugs['vim-kitty-navigator'].commit = 'f09007be7e477a491a478444b302d079104af23d'
silent! let g:plugs['vim-lastplace'].commit = '8f6c4454eb462776b6ebdc48e3e29a68ddeb726d'
silent! let g:plugs['vim-numbertoggle'].commit = '97f2a3c7e9ab769686a5f29109bd1a297c7461e1'
silent! let g:plugs['vim-prettier'].commit = 'e7564653bccc34a2564ccd9463483af2965d148e'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'
silent! let g:plugs['wildfire.vim'].commit = 'e2baded7162260e05d2527f5bca9fca81f0bc8f2'

PlugUpdate!

