" Generated by vim-plug
" Tue 20 Jul 2021 10:03:28 AM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['galaxyline.nvim'].commit = 'd544cb9d0b56f6ef271db3b4c3cf19ef665940d5'
silent! let g:plugs['gitsigns.nvim'].commit = '66638c929c61f950246f3d292b6157a9596241de'
silent! let g:plugs['jqno-autoclose.vim'].commit = '8e379b5e701ec2e31b9ebbd5e4b69bb535954c91'
silent! let g:plugs['nord-vim'].commit = '8d8b9bf86bbc715a055b54cb53f0643fd664caa4'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-compe'].commit = 'ef97a9b17c655d8b603c5fa9abf6fbb623a1dad4'
silent! let g:plugs['nvim-dap'].commit = '344b6f0b581dd72e40bbbb78b4f147e5003e0ce6'
silent! let g:plugs['nvim-jdtls'].commit = '391e55bb5f90bc23e47c3b57eed6c6fcc95b0e7f'
silent! let g:plugs['nvim-lspconfig'].commit = 'f97aac6b717e904fe4d8ff58425651d5a802084e'
silent! let g:plugs['nvim-lspinstall'].commit = '6752b31295bf410d8768f7f3bac15e6f1f5b8fbf'
silent! let g:plugs['nvim-metals'].commit = '32fc0b137407b169e01cbc762844cdbfacacfe4f'
silent! let g:plugs['nvim-tree.lua'].commit = 'd3e76b81e5b169af192dea4da0bd6f64faad2c36'
silent! let g:plugs['nvim-treesitter'].commit = '61e87b2f9cbd3f4740e4721e1165db351e9b32da'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '7f36db566c66998e04ea569723174c42d8190903'
silent! let g:plugs['plenary.nvim'].commit = '8bae2c1fadc9ed5bfcfb5ecbd0c0c4d7d40cb974'
silent! let g:plugs['popup.nvim'].commit = '5e3bece7b4b4905f4ec89bee74c09cfd8172a16a'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = '46e03a935f1d080a9bd856d5a8acfcc093cd1461'
silent! let g:plugs['terminus'].commit = 'e8bc19c8156d955762c31d0964eeb7c84889f42e'
silent! let g:plugs['ultisnips'].commit = 'aec91caefec10741722927cf073703a528fe7a8f'
silent! let g:plugs['vim-closetag'].commit = 'c0779ef575d5c239162f4ca3506cfb4a95d45a58'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-cool'].commit = '27ad4ecf7532b750fadca9f36e1c5498fc225af2'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-gutentags'].commit = '50705e8ebb7038b31314f416d1bddd9cb9154049'
silent! let g:plugs['vim-lastplace'].commit = '8f6c4454eb462776b6ebdc48e3e29a68ddeb726d'
silent! let g:plugs['vim-numbertoggle'].commit = '075b7478777e694fbac330ee34a74590dad0fee1'
silent! let g:plugs['vim-prettier'].commit = '0e61e4a5b55d2740aa118db91a6671dcb11307e8'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'
silent! let g:plugs['which-key.nvim'].commit = 'dc9c3be7acae2a486c117f5a9f6ada62b2243336'
silent! let g:plugs['wildfire.vim'].commit = 'fa91b732fd1c5acd23b7b32d5fbbc884eedafc8d'
silent! let g:plugs['zen-mode.nvim'].commit = '21ca264c6ae934ceac220cf719c0ed6c0216b057'

PlugUpdate!

