" Generated by vim-plug
" Wed 09 Jun 2021 01:52:34 PM CEST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['galaxyline.nvim'].commit = 'cbf64bd4869c810b92f6450ed8763456c489be87'
silent! let g:plugs['gitsigns.nvim'].commit = '6b7b666cc95f91c869b1ef266e10f06807f7ccf0'
silent! let g:plugs['jqno-autoclose.vim'].commit = '479270a6d78e813e46a4b706566347909196f29f'
silent! let g:plugs['lspsaga.nvim'].commit = '2bc15f3c9851613fa29926780914d25ebc4b8c83'
silent! let g:plugs['nvcode-color-schemes.vim'].commit = '90ee71d66da58d57f0cb4a59103874bb519c79d4'
silent! let g:plugs['nvim-colorizer.lua'].commit = '36c610a9717cc9ec426a07c8e6bf3b3abcb139d6'
silent! let g:plugs['nvim-compe'].commit = '888d9eccfe7b9092dcbfcdfabfad601ce63f3eb5'
silent! let g:plugs['nvim-dap'].commit = '260d13945348966f695c46e4c711001066f47300'
silent! let g:plugs['nvim-jdtls'].commit = '3c5d3b209a6312d47338ff71779d7be568ee67c0'
silent! let g:plugs['nvim-lspconfig'].commit = '0a921bf2be74d293c8a8d6dd70122c1d01151a30'
silent! let g:plugs['nvim-lspinstall'].commit = '7203abe8ae9daac70c03771555106ff65876c91d'
silent! let g:plugs['nvim-metals'].commit = '69a5cf9380defde5be675bd5450e087d59314855'
silent! let g:plugs['nvim-tree.lua'].commit = 'f39869514645b98ec30bc8826763c288b6cbdbef'
silent! let g:plugs['nvim-treesitter'].commit = '9e0f764b675d987bbdd45af38531cc864c8cfc4c'
silent! let g:plugs['nvim-treesitter-textobjects'].commit = '522b26a8795994b719a921a03cfacb0d7dcabf78'
silent! let g:plugs['plenary.nvim'].commit = '3f993308024697186c02d51df1330bf07c12535a'
silent! let g:plugs['popup.nvim'].commit = '5e3bece7b4b4905f4ec89bee74c09cfd8172a16a'
silent! let g:plugs['telescope-fzy-native.nvim'].commit = '7b3d2528102f858036627a68821ccf5fc1d78ce4'
silent! let g:plugs['telescope.nvim'].commit = 'c061c216bfe082384d542a487ce02e9aed6177df'
silent! let g:plugs['terminus'].commit = '51c9bf43427af5ddff7352707a2bdab58cac9593'
silent! let g:plugs['ultisnips'].commit = 'b974a13328071de45a85c62ab65c8bfed0142728'
silent! let g:plugs['vim-closetag'].commit = 'c0779ef575d5c239162f4ca3506cfb4a95d45a58'
silent! let g:plugs['vim-commentary'].commit = '349340debb34f6302931f0eb7139b2c11dfdf427'
silent! let g:plugs['vim-cool'].commit = '27ad4ecf7532b750fadca9f36e1c5498fc225af2'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-eunuch'].commit = 'dbbbf853fc523d312f61b4bbdf2e13297645dcde'
silent! let g:plugs['vim-gutentags'].commit = '50705e8ebb7038b31314f416d1bddd9cb9154049'
silent! let g:plugs['vim-kitty-navigator'].commit = 'f09007be7e477a491a478444b302d079104af23d'
silent! let g:plugs['vim-lastplace'].commit = '8f6c4454eb462776b6ebdc48e3e29a68ddeb726d'
silent! let g:plugs['vim-numbertoggle'].commit = '97f2a3c7e9ab769686a5f29109bd1a297c7461e1'
silent! let g:plugs['vim-prettier'].commit = 'e7564653bccc34a2564ccd9463483af2965d148e'
silent! let g:plugs['vim-sandwich'].commit = '9e6340affe9f53c11a6975a5f50b9bf48adb692c'
silent! let g:plugs['vimwiki'].commit = '619f04f89861c58e5a6415a4f83847752928252d'
silent! let g:plugs['which-key.nvim'].commit = '20a85bd8bc54a11cf040aafa5d60f8a735eecfbd'
silent! let g:plugs['wildfire.vim'].commit = 'e2baded7162260e05d2527f5bca9fca81f0bc8f2'
silent! let g:plugs['zen-mode.nvim'].commit = 'f90fd8ddbbb0516416a372ce15f9b7cf40a6c233'

PlugUpdate!

