.PHONY: clean compile test verify format

default: help

help:
	@echo "TODO: send help"

clean:
	mvn clean

compile:
	mvn test-compile

test:
	mvn test

verify:
	mvn verify

format:
	mvn spotless:apply
