#!/usr/bin/env bash

# Adapted from https://medium.com/@GroundControl/better-git-diffs-with-fzf-89083739a9cb

preview="git diff $@ --color=always -- {-1}"
git diff "$@" --name-only | fzf -m --ansi --preview "$preview"
