# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Custom scripts
source ~/.zsh/init.zsh
source ~/.zsh/functions.sh
source ~/.zsh/environment.sh
source ~/.zsh/aliases.sh
source ~/.zsh/hotkeys.sh
source ~/.zsh/completion.zsh
source ~/.zsh/vim-terminal-mode.sh
#source ~/.setEnv/session.sh

# Zsh plugins
#source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Enable FZF
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
if [[ "$(uname -s)" == "Darwin" ]]; then
  export SDKMAN_DIR="/Users/jqno/.sdkman"
elif [[ "$(uname -s)" == "Linux" ]]; then
  export SDKMAN_DIR="/home/jqno/.sdkman"
fi
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

# Enable Powerlevel10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source $HOME/bin/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh

