# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory

# Settings
setopt autocd nomatch
unsetopt beep extendedglob notify

# Completions
zstyle :compinstall filename '/Users/jqno/.zshrc'
autoload -Uz compinit
compinit

# VIM mode
bindkey -v
export KEYTIMEOUT=1
export EDITOR=vim

# Source my scripts (including fancy prompt!)
for f in ~/.zsh/*; do
  . $f
done

# Auto-suggesions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^[[Z' autosuggest-accept  # Shift-tab

# Syntax highlighting (must be at the end of .zshrc!)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

